### ISSUE TITLE
Python CI Test Failures

### ISSUE THREAD

**Issue by jared321** [POptUS/IBCDFO#168]
I recently added in Python 3.9 tests to the CI actions in PR #167, but had to exclude macOS-14 and -15 test setups with 3.9 due to failures.

A failed execution can be found at
https://github.com/POptUS/IBCDFO/actions/runs/12322074834/job/34394854098

I see at least the error messages
```
Traceback (most recent call last):
  File "/Users/runner/work/IBCDFO/IBCDFO/ibcdfo_pypkg/.tox/nocoverage/lib/python3.9/site-packages/ibcdfo/pounders/tests/TestPoundersExtensive.py", line 84, in test_benchmark_pounders
    self.assertTrue(evals == nf_max + nfs, "POUNDERs didn't use nf_max evaluations")
AssertionError: False is not true : POUNDERs didn't use nf_max evaluations
```
and
```
======================================================================
FAIL: test_pounders_one_output (TestPoundersSimple.TestPounders)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/IBCDFO/IBCDFO/ibcdfo_pypkg/.tox/nocoverage/lib/python3.9/site-packages/ibcdfo/pounders/tests/TestPoundersSimple.py", line 138, in test_pounders_one_output
    self.assertTrue(flag == -6, "This test should hit the mindelta termination.")
AssertionError: False is not true : This test should hit the mindelta termination.
```

**Comment by jared321** [comment]
After speaking with Matt recently, I understand that the fact that this test returns `flag=-2` is neither surprising nor indicative of a bug.  Rather, it's a reality of the nature of the test case.

@mmenickelly @jmlarson1 Have your investigations of this issue finished?  If so, can I include in Issue #227 the task of dropping Python 3.9 support and close this issue?
